wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: huggingface
    huggingface_version: 4.9.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1673525521
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      3:
      - 13
      - 15
      - 16
      4: 3.7.13
      5: 0.12.4
      6: 4.9.2
      8:
      - 5
batch_size:
  desc: null
  value: 12
checkpoint_path:
  desc: null
  value: /tmp/XAlign/checkpoint
clip_grad_norm:
  desc: null
  value: 0.0
complete_coverage:
  desc: null
  value: 0
dataset_path:
  desc: null
  value: /tmp/XAlign/datasets
dropout_rate:
  desc: null
  value: 0.1
enable_bleu_cal_per_epoch:
  desc: null
  value: 0
enable_scheduler:
  desc: null
  value: false
enable_script_unification:
  desc: null
  value: 1
epochs:
  desc: null
  value: 30
eval_batch_size:
  desc: null
  value: 12
eval_beams:
  desc: null
  value: 5
gpus:
  desc: null
  value: 4
inference:
  desc: null
  value: false
lang:
  desc: null
  value:
  - as
  - bn
  - en
  - gu
  - hi
  - kn
  - ml
  - mr
  - or
  - pa
  - ta
  - te
learning_rate:
  desc: null
  value: 0.001
length_penalty:
  desc: null
  value: 1.0
logger_exp_name:
  desc: null
  value: as-bn-en-gu-hi-kn-ml-mr-or-pa-ta-te-google-mt5-small-30-0.001-unified-script
model_name:
  desc: null
  value: google/mt5-small
online_mode:
  desc: null
  value: 1
patience:
  desc: null
  value: 10
src_max_seq_len:
  desc: null
  value: 200
test_dataset_count:
  desc: null
  value: 0
tgt_max_seq_len:
  desc: null
  value: 200
train_dataset_count:
  desc: null
  value: 0
use_pretrained:
  desc: null
  value: 1
val_dataset_count:
  desc: null
  value: 0
verbose:
  desc: null
  value: true
verbose_output_dir:
  desc: null
  value: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/model_outputs
warmup_steps:
  desc: null
  value: 4000
weight_decay:
  desc: null
  value: 0.01
