wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.13
    start_time: 1680810571
    t:
      1:
      - 1
      - 2
      - 3
      - 9
      - 11
      2:
      - 1
      - 2
      - 3
      - 9
      - 11
      3:
      - 16
      - 17
      4: 3.7.13
      5: 0.12.4
      6: 4.27.4
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 2
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 2.0e-05
